version: "3.9"

services:
  postgres:
    image: postgres:17
    container_name: cadp-postgres
    ports:
      - "5433:5432"   # ðŸ‘ˆ change host port

    environment:
      POSTGRES_DB: cadp_db
      POSTGRES_USER: cadp_user
      POSTGRES_PASSWORD: cadp_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
